- hosts: host
  become: yes
  tasks:

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Скачивание зависимостей
      apt:
        name:
        - curl
        - ca-certificates
        - python3
        - python3-psycopg2
        state: present

    - name: Создание директории для ключей
      file:
        path: /etc/apt/keyrings
        mode: '0755'
        state: directory

    - name: Добавление ключа docker
      get_url:
        url: "https://download.docker.com/linux/debian/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Добавление репозитория docker
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        mode: '0644'
        update_cache: yes

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка docker
      apt:
        name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Копирование папки с docker-compose
      copy:
        src: ./nginx
        dest: /root/nginx
        owner: root
        group: root
        mode: '0777'

    - name: Запуск контейнера с сервером и бд
      command: docker compose -f /root/nginx/nginx/docker-compose.yml up -d

    - name: Установка logrotate
      apt:
        name:
          - logrotate
        state: present

    - name: Копирование конф файла logrotate
      copy:
        src: ./rsyslog
        dest: /etc/logrotate.d/rsyslog
        owner: root
        group: root
        mode: '0644'

    - name: Перезапуск logrotate
      systemd:
        name: logrotate
        state: restarted