services:
    postgres:
        image: postgres:16-alpine
        ports:
          - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: main
            POSTGRES_PASSWORD: StrongPa$$1Word
            POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost all all 0.0.0.0/0 md5"
            POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
        volumes:
          - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        logging:
            options:
                mode: "non-blocking"
                max-size: "200k"
                max-file: "10"
        hostname: postgres

    web:
        image: nginx:latest
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/index.php:/var/www/html/index.php"
            - "./etc/restricted/restricted.html:/var/www/restricted/restricted.html"
        expose:
            - "80"
        restart: always
        depends_on:
            - php
        hostname: web

    php:
        image: nanoninja/php-fpm:latest
        restart: always
        volumes:
            - "./etc/nginx/index.php:/var/www/html/index.php"

    proxy:
        image: nginx:latest
        volumes:
            - ./etc/proxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "4000:4000"
        restart: always
        logging:
            options:
                mode: "non-blocking"
                max-size: "200k"
                max-file: "10"
        depends_on:
            - web

    postgres-exporter:
        image: prometheuscommunity/postgres-exporter
        expose:
            - "9187"
        environment:
            DATA_SOURCE_NAME: "postgresql://postgres:StrongPa$$1Word@postgres:5432/main?sslmode=disable"

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter
        expose:
            - "9113"
        command:
            - -nginx.scrape-uri=http://web:80/stub_status

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        expose:
            - "9100"

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - ./etc/grafana/grafana.db:/var/lib/grafana/grafana.db

    waf:
        image: ghcr.io/openappsec/agent
        volumes:
            - ./etc/waf/conf:/etc/cp/conf
            - ./etc/waf/data:/etc/cp/data
            - ./etc/waf/logs:/var/log/nano_agent
            - ./etc/waf/localconf:/ext/appsec
        environment:
            - registered_server='NGINX Server'
            - AGENT_TOKEN=cp-d9c8de1d-470b-4d3a-8fba-48a791779ccf5cdeac0c-b0c5-4f3e-8a99-24d55ed0de69
        command: /cp-nano-agent

networks:
  default:
    driver: bridge
    name: web